### PR TITLE
Preload placeholder image not being properly displayed - Fix issue #23

### PR DESCRIPTION
**Pull request by davidrissato**
Fix issue #23

### CODE REVIEW

**Comment by bicknellr** [comment]
Could you add a test or two for this?

**Comment by davidrissato** [comment]
Ok, I'll add them in a couple days.

**Comment by davidrissato** [comment]
@bicknellr I'm trying to implement some tests to this problem, but I believe I need to go deep in the shadowed elements to expose the problem. I'm not an expert in HTML tests. Can I do that? I think if I do this way my tests will fail in case of internal refactoring.

**Comment by bicknellr** [comment]
I've been trying to group together a handful of fixes in #44 and I've added a test there for the issue this PR is addressing. I think you're right, there doesn't appear to be a good way to test this without reaching into the internals. :/

**Comment by davidrissato** [comment]
@bicknellr Yes. So I'm a little bit confused. Will you use this pull or have you already added these changes in #44? Do you still need that I add tests here?

**Comment by bicknellr** [comment]
@davidrissato Sorry about stepping on your toes here! It seemed like a few different issues could be resolved by refactoring iron-image to use a single img element internally - #23 being one of them - so don't worry about pushing tests for this PR. However, it would be great to get your confirmation that #44 correctly tests for / fixes #23.

**Comment by davidrissato** [comment]
Ok, no problem. This solution was based on a single img element too, so I believe you are addressing it as well. I'll check #44 and verify if it really fixes all #23 reported problems.
By the way, should we close this pull request?

**Comment by bicknellr** [comment]
Sounds good, thanks!

**Pull request closed without merging**
