### PR TITLE
Fix for non-regular image source URLs

### LINKED ISSUE #32: this.style.backgroundImage needs quotes
I had an issue with a URL that did not load when using the sizing property. I changed the code and it works now.

Before:
```
        this.style.backgroundImage = this.src ? 'url(' + this.src + ')': '';
```
After:
```
        this.style.backgroundImage = this.src ? 'url("' + this.src + '")': '';
```

The example markup was:
```
<iron-image sizing="cover" style="width: 400px; height: 400px" preload src="uploads/screenshot-modesto craigslist org 2015-06-08 22-42-27.png"></iron-image>
```

I can submit a pull request for this if necessary.

### PR DESCRIPTION
**Pull request by alefwmm**
Just adding quotes to the image source URL

(Added by @bicknellr: Fixes #32.)

### CODE REVIEW

**Comment by alefwmm** [comment]
I signed it!

**Comment by rchrd2** [comment]
:+1:

**Comment by alefwmm** [comment]
@bicknellr Test added. And working!

**Comment by bicknellr** [comment]
#32 is closed as of v1.1.0, but thanks for submitting this!

**Pull request closed without merging**
