### PR TITLE
Fix #86: Provide base URI to URL constructor.

### LINKED ISSUE #86: Exception with absolute URLs on Polymer 1.6.1
### Description
A [very recent change in Polymer](https://github.com/Polymer/polymer/commit/94f95ece3af7a4f70e0f1a419287c2cd2bd64fcf)  due to https://github.com/Polymer/polymer/issues/2448 causes the following exception to be thrown when using an absolute URL as the image `src`:

```
VM1527:1 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at TypeError (native)
    at eval (eval at evaluate (unknown source), <anonymous>:1:1)
    at iron-image._computeImgDivARIALabel (http://localhost:3001/assets/application-658e89886904e8ba3c8a9b98211302f287e1e8e6f5f8aa17ac61a231bfd0ac6f.html:19972:31)
    at iron-image._annotatedComputationEffect (http://localhost:3001/assets/application-658e89886904e8ba3c8a9b98211302f287e1e8e6f5f8aa17ac61a231bfd0ac6f.html:4494:24)
```

I think this is because `new URL()` expects a full URL with domain and protocol but now `Polymer.ResolveUrl.resolveUrl()` is returning the original absolute path without modification.

I think the solution is to change https://github.com/PolymerElements/iron-image/blob/e5872b807f52d1562dd45905e5a2a44d6f9b0c42/iron-image.html#L342 to supply the second parameter for `URL()` (`this.ownerDocument.baseURI`).

### Steps to reproduce
1. Add an `iron-image` element with an absolute path as the `src` attribute and no `alt` value set.

### PR DESCRIPTION
**Pull request by bicknellr**
`_resolveSrc` now returns a complete URL.

### CODE REVIEW

**Comment by bicknellr** [comment]
@azakus, should Polymer/polymer#2448 be considered a general policy that applies to elements also?

**Comment by bicknellr** [comment]
FYI, `_resolveSrc` returns a URL that represents the absolute path to the element which is cached so we can compare later whether or not a change to `src` should actually change the `src` attribute of the wrapped img. (For example, for a page 'http://example.com/folder/page.html', changing an iron-image with `src` of 'image.png' to '../folder/image.png' wouldn't cause the img's `src` attribute to be changed.)

**Comment by kevin-wise-infusionsoft** [comment]
Can we get this merged please?  #86breaks our whole site so we're faced with having to roll back to 1.6.0.

**Comment by azakus** [comment]
@bicknellr The fix to Polymer/polymer#2448 just treats more urls given to`resolvePath` as absolute. You are right that it is not guaranteed that the result of `resolvePath` is a valid input to `new URL()`.

This change LGTM as it is more robust.

**Comment by bicknellr** [comment]
@kevin-wise-infusionsoft Just to be clear, you've tried with this branch and it works as expected?

**Comment by kevin-wise-infusionsoft** [comment]
Yes, on the branch the issue is resolved. I haven't exhaustively tested to see if it causes any issues, but it seems pretty safe.

**Comment by bicknellr** [comment]
Alright, I was worried that this would cause problems for URLs in components wrapping iron-image but @azakus told me that Polymer will have already resolved URL given to `src` relative to the document that URL was used in, so it shouldn't be a problem using `this.ownerDocument.baseURI` with everything.

**Pull request merged**
