### PR TITLE
Call _loadBehaviorChanged when src property changes to set up a new I…

### LINKED ISSUE #16: Bad state possible when reusing the element with multiple images
Seeing this with iron-list currently, but I believe this is a general issue when re-using the element with multiple images. Reproduction:

1. Set preload to true on an iron-image element.
2. Set the src property to an image that is not available.
3. The placeholder is correctly shown.
4. Now set the src property to an available image.

Result:
The placeholder still shows.
Expected:
The available image should show.

### PR DESCRIPTION
**Pull request by sfeast**
…mage object & onload handler. Fixes #16

### CODE REVIEW

**Comment by davidrissato** [comment]
This change doesn't fix if when the image is inside an iron-list.

I got it fixed just adding the following line:

```
    _srcChanged: function(newSrc, oldSrc) {
      if (newSrc !== oldSrc) {
        this.loaded = false;
        this.style.backgroundImage = null;   // Adding this line remove the "phantom" image under the placeholder
      }
    },
```

**Comment by sfeast** [comment]
Hmm not too sure what you're fixing here, might be something else. This pull request is for issue #16 which was first noticed with re-used iron-image's in iron-list. You might want to submit a separate pull request for your finding.

**Comment by davidrissato** [comment]
I have some changes that you might include in this fix. They are related to preLoad functions which were behaving erratically.

My changes fixes those issues when iron-image is reused (in an iron-list for example):
- Preload image being displayed over the last image loaded
- Preload image being hidden before the new image is fully loaded (when you change image src quickly)

What can I do to contribute with those changes?

**Comment by ronnyroeller** [comment]
+1, PR fixes the issue that changing values for the 'src' property are not reflected. If the src is calculated async, the image is not loaded at without the PR.

**Comment by bicknellr** [comment]
v1.1.0 should handle this case.

**Pull request closed without merging**
