### PR TITLE
Update to Polymer 1.1

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by abdonrd** [comment]
PR updated! :)

**Comment by abdonrd** [comment]
PR rebased!

Friendly ping to @bicknellr because the PR has months old. :)

**Comment by bicknellr** [comment]
Just merged another PR with a messy diff, could you rebase again?

**Comment by abdonrd** [comment]
@bicknellr rebased! :dizzy:

**Comment by bicknellr** [comment]
Thanks! LGTM

**Pull request merged**
